server:
  port: 8081

spring:
  application:
    name: UserServiceApps

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/GrpcTestDb
    username: grpc_user
    password: 321321

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: order-message-events

grpc:
  client:
    order-service:
      address: static://localhost:9082
      negotiationType: plaintext